name: Build
on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "**" ]
  pull_request:
  release:
    types: [ released ]

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
      fail-fast: true
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/wrapper-validation@v5
      - name: JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build
        run: ./gradlew build --stacktrace
#
#      - name: Publish Release
#        if: "${{ github.event_name == 'release' }}"
#        run: ./gradlew publish --stacktrace
#        env:
#          ORG_GRADLE_PROJECT_paperUsername: "${{ secrets.CI_USER }}"
#          ORG_GRADLE_PROJECT_paperPassword: "${{ secrets.CI_PASS }}"
